
CREATE TABLE COMPANY
(
  ID      VARCHAR(200) NOT NULL COMMENT '유니크 ID',
  NAME    VARCHAR(200) NOT NULL COMMENT '이름',
  AGE     INT          NOT NULL COMMENT '나이',
  ADDRESS CHAR(50)     NULL     COMMENT '주소',
  SALARY  REAL         NOT NULL COMMENT '월급',
  PRIMARY KEY (ID )
) COMMENT '회사 구성원';

CREATE TABLE DEPAPTMET
(
  ID      VARCHAR(200) NOT NULL COMMENT '유니크 ID',
  DEPT    VARCHAR(200) NOT NULL COMMENT '부서',
  EMP_ID  VARCHAR(200) NOT NULL COMMENT '유니크 ID',
  PRIMARY KEY (ID)
) COMMENT '부서';

ALTER TABLE DEPAPTMET
  ADD CONSTRAINT FK_COMPANY_TO_DEPAPTMET
    FOREIGN KEY (EMP_ID )
    REFERENCES COMPANY (ID );
